version: '3.9'

services:
  client:
    image: cloudcarbonfootprint/client:release-2023-10-17
    restart: always
    ports:
      - '8000:80'
    volumes:
      - /home/lylla/cloud-carbon-footprint/docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    environment:
      - NODE_OPTIONS=--max-old-space-size=2048

  api:
    image: cloudcarbonfootprint/api:release-2023-10-17
    restart: always
    environment:
      - CACHE_MODE=LOCAL
      - AZURE_USE_BILLING_DATA=true
      - AZURE_CLIENT_ID=/run/secrets/AZURE_CLIENT_ID
      - AZURE_CLIENT_SECRET=/run/secrets/AZURE_CLIENT_SECRET
      - AZURE_TENANT_ID=/run/secrets/AZURE_TENANT_ID 
      - AZURE_CONSUMPTION_CHUNKS_DAYS=3
      - AZURE_SUBSCRIPTIONS="73950e61-893d-4b97-84ea-3a0b33335d0b"
      - NODE_OPTIONS=--max-old-space-size=4096
        
secrets:
  AZURE_CLIENT_ID:
    file: ~/.docker/secrets/AZURE_CLIENT_ID
  AZURE_CLIENT_SECRET:
    file: ~/.docker/secrets/AZURE_CLIENT_SECRET
  AZURE_TENANT_ID:
    file: ~/.docker/secrets/AZURE_TENANT_ID
